### ISSUE TITLE
Boundary.com Maven repo is down, dependencies can't be resolved.

### ISSUE THREAD

**Issue by jamesbloomer** [zcourts/higgs#25]
http://maven.boundary.com/artifactory/ is down which means that the high-scale-lib cannot be resolved. I notice that they have also put the library in bintray I wonder whether it's worth considering using that repo? (https://bintray.com/bintray/jcenter/com.boundary%3Ahigh-scale-lib/view#files)

**Comment by zcourts** [comment]
@AndyJS / @jamesbloomer addressed by 0.0.16 release https://github.com/zcourts/higgs/releases/tag/higgs-0.0.16 (No dependency on third party repos)
